language: php

sudo: false

addons:
    apt:
        packages:
            - aspell
            - aspell-en
            - aspell-de
            - aspell-cs

php:
    - '7.2'

before_script:
    - cd $TRAVIS_BUILD_DIR/linter
    - travis_wait composer install

script:
    - php lint
